from django.urls import path
from .views import *

urlpatterns = [
    path('announcements/', AnnouncementsAPI.as_view()),
    path('announcements/<int:id>/', AnnouncementsAPI.as_view()),
    path('banners/', BannersAPI.as_view()),
    path('banners/<int:id>', BannersAPI.as_view()),
    path('event-banners/', EvBannersAPI.as_view()),
    path('event-banners/<int:id>/', EvBannersAPI.as_view()),
    path('events/', EventsAPI.as_view()),
    path('events/<int:id>/', EventsAPI.as_view()),
    path('majors/', MajorsAPI.as_view()),
    path('majors/<int:id>/', MajorsAPI.as_view()),
    path('org-cat/', OrganizationCatAPI.as_view()),
    path('org-cat/<int:id>/', OrganizationCatAPI.as_view()),
    path('organizations/', OrganizationAPI.as_view()),
    path('organizations/<int:id>/', OrganizationAPI.as_view()),
    path('regulations/', RegulationAPI.as_view()),
    path('regulations/<int:id>/', RegulationAPI.as_view()),
    path('scholarships/', ScholarshipAPI.as_view()),
    path('scholarships/<int:id>/', ScholarshipAPI.as_view()),
    path('semesters/', SemestersAPI.as_view()),
    path('semesters/<int:id>/', SemestersAPI.as_view()),
    path('shortlinks/', ShortlinksAPI.as_view()),
    path('shortlinks/<int:id>/', ShortlinksAPI.as_view()),
    # path('students/', StudentsAPI.as_view()),
    # path('students/<int:id>/', StudentsAPI.as_view()),
    path('study-program/', StudyProgramAPI.as_view()),
    path('study-program/<int:id>/', StudyProgramAPI.as_view()),
    path('subjects/', SubjectsAPI.as_view()),
    path('subjects/<int:id>/', SubjectsAPI.as_view()),
    path('wsb/', WhistleblowsAPI.as_view()),
    path('wsb/<int:id>/', WhistleblowsAPI.as_view()),
]